# Generated by Django 3.2.12 on 2023-09-12 06:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mysetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='MyApp', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('facbook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('theme_color', colorfield.fields.ColorField(blank=True, default='#10284e', image_field=None, max_length=25, samples=None)),
                ('logo', models.ImageField(blank=True, upload_to='photos/img/')),
            ],
        ),
    ]
