# Generated by Django 3.2.12 on 2023-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_contact_productlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='HSN_Code',
            field=models.CharField(error_messages={'required': 'Please enter HSN Code'}, max_length=200, unique=True),
        ),
    ]
