# Generated by Django 3.2.12 on 2023-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230912_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
