# Generated by Django 3.2.12 on 2023-09-12 10:29

import datetime
from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSN_Code', models.CharField(max_length=200, verbose_name=myapp.models.ProductListing)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('seeling_price', models.IntegerField(verbose_name=myapp.models.ProductListing)),
                ('discounted_price', models.IntegerField(default=0)),
                ('gram', models.DecimalField(decimal_places=1, max_digits=2)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('purchase_mode', models.CharField(default='offline', max_length=100)),
                ('saller', models.CharField(default='shop', max_length=200)),
            ],
        ),
    ]
