# Generated by Django 3.2.12 on 2023-09-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_productlisting_discount'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='HSN_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.productlisting'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seeling_price',
            field=models.IntegerField(default=0),
        ),
    ]
