# Generated by Django 3.2.12 on 2023-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_gram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
