# Generated by Django 3.2.12 on 2023-09-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='HSN_Code',
            field=models.CharField(max_length=200),
        ),
    ]
